// Product data array for the e-commerce app
// Each object represents a product with its details such as name, category, brand, price, color, material, rating, and image
// This data is used to populate the product catalog and for filtering/searching in the frontend

 const products = [
  {
    id: 1,
    name: "iPhone 15 Pro", // Product name
    category: "Electronics", // Product category
    brand: "Apple", // Brand name
    price: 999, // Price in USD
    color: "Space Black", // Color variant
    storage: "128GB", // Storage capacity
    material: "Titanium", // Material used
    rating: 4.8, // Customer rating
    image: "📱" // Emoji or image representing the product
  },
  {
    id: 2,
    name: "Samsung Galaxy S24",
    category: "Electronics",
    brand: "Samsung",
    price: 799,
    color: "Phantom Black",
    storage: "256GB",
    material: "Aluminum",
    rating: 4.6,
    image: "📱"
  },
  {
    id: 3,
    name: "MacBook Pro 14\"",
    category: "Electronics",
    brand: "Apple",
    price: 1999,
    color: "Space Gray",
    storage: "512GB",
    material: "Aluminum",
    rating: 4.9,
    image: "💻"
  },
  {
    id: 4,
    name: "Sony WH-1000XM5",
    category: "Electronics",
    brand: "Sony",
    price: 399,
    color: "Black",
    storage: "N/A",
    material: "Plastic",
    rating: 4.7,
    image: "🎧"
  },
  {
    id: 5,
    name: "Nike Air Max 270",
    category: "Apparel",
    brand: "Nike",
    price: 150,
    color: "White",
    size: "US 10",
    material: "Mesh",
    rating: 4.4,
    image: "👟"
  },
  {
    id: 6,
    name: "Adidas Ultraboost 22",
    category: "Apparel",
    brand: "Adidas",
    price: 180,
    color: "Black",
    size: "US 9",
    material: "Primeknit",
    rating: 4.5,
    image: "👟"
  },
  {
    id: 7,
    name: "Levi's 501 Original Jeans",
    category: "Apparel",
    brand: "Levi's",
    price: 89,
    color: "Blue",
    size: "32W x 34L",
    material: "Denim",
    rating: 4.3,
    image: "👖"
  },
  {
    id: 8,
    name: "Champion Hoodie",
    category: "Apparel",
    brand: "Champion",
    price: 45,
    color: "Gray",
    size: "L",
    material: "Cotton",
    rating: 4.2,
    image: "👕"
  },
  {
    id: 9,
    name: "The Great Gatsby",
    category: "Books",
    brand: "Scribner",
    price: 15,
    color: "Blue",
    pages: "180",
    material: "Paperback",
    rating: 4.1,
    image: "📚"
  },
  {
    id: 10,
    name: "To Kill a Mockingbird",
    category: "Books",
    brand: "Harper Lee",
    price: 12,
    color: "Green",
    pages: "376",
    material: "Hardcover",
    rating: 4.6,
    image: "📚"
  },
  {
    id: 11,
    name: "1984",
    category: "Books",
    brand: "Penguin Classics",
    price: 14,
    color: "Red",
    pages: "328",
    material: "Paperback",
    rating: 4.7,
    image: "📚"
  },
  {
    id: 12,
    name: "Instant Pot Duo 7-in-1",
    category: "Home & Kitchen",
    brand: "Instant Pot",
    price: 99,
    color: "Stainless Steel",
    capacity: "6 Quart",
    material: "Stainless Steel",
    rating: 4.5,
    image: "🍲"
  },
  {
    id: 13,
    name: "KitchenAid Stand Mixer",
    category: "Home & Kitchen",
    brand: "KitchenAid",
    price: 349,
    color: "Red",
    capacity: "5 Quart",
    material: "Metal",
    rating: 4.8,
    image: "🥄"
  },
  {
    id: 14,
    name: "Dyson V15 Detect",
    category: "Home & Kitchen",
    brand: "Dyson",
    price: 749,
    color: "Yellow",
    capacity: "0.76L",
    material: "Plastic",
    rating: 4.6,
    image: "🧹"
  },
  {
    id: 15,
    name: "Ninja Blender",
    category: "Home & Kitchen",
    brand: "Ninja",
    price: 89,
    color: "Black",
    capacity: "72oz",
    material: "Plastic",
    rating: 4.4,
    image: "🥤"
  },
   {
    "id": 50,
    "name": "Echo Dot 6th Gen",
    "category": "Electronics",
    "brand": "Amazon",
    "price": 59,
    "color": "Charcoal",
    "storage": "N/A",
    "material": "Plastic",
    "rating": 4.4,
    "image": "🔊"
  },
  {
    "id": 51,
    "name": "Fitbit Versa 4",
    "category": "Electronics",
    "brand": "Fitbit",
    "price": 199,
    "color": "Midnight Blue",
    "storage": "N/A",
    "material": "Aluminum",
    "rating": 4.3,
    "image": "⌚"
  },
  {
    "id": 52,
    "name": "Dell XPS 13",
    "category": "Electronics",
    "brand": "Dell",
    "price": 1299,
    "color": "Platinum Silver",
    "storage": "256GB",
    "material": "Aluminum",
    "rating": 4.7,
    "image": "💻"
  },
  {
    "id": 53,
    "name": "Bose QuietComfort Ultra",
    "category": "Electronics",
    "brand": "Bose",
    "price": 379,
    "color": "White Smoke",
    "storage": "N/A",
    "material": "Plastic",
    "rating": 4.8,
    "image": "🎧"
  },
  {
    "id": 54,
    "name": "Puma RS-X",
    "category": "Apparel",
    "brand": "Puma",
    "price": 120,
    "color": "Gray",
    "size": "US 11",
    "material": "Mesh",
    "rating": 4.4,
    "image": "👟"
  },
  {
    "id": 55,
    "name": "Under Armour Tech Tee",
    "category": "Apparel",
    "brand": "Under Armour",
    "price": 35,
    "color": "Black",
    "size": "M",
    "material": "Polyester",
    "rating": 4.2,
    "image": "👕"
  },
  {
    "id": 56,
    "name": "Wrangler Classic Jeans",
    "category": "Apparel",
    "brand": "Wrangler",
    "price": 49,
    "color": "Dark Blue",
    "size": "34W x 32L",
    "material": "Denim",
    "rating": 4.3,
    "image": "👖"
  },
  {
    "id": 57,
    "name": "Columbia Fleece Jacket",
    "category": "Apparel",
    "brand": "Columbia",
    "price": 65,
    "color": "Navy",
    "size": "L",
    "material": "Fleece",
    "rating": 4.5,
    "image": "🧥"
  },
  {
    "id": 58,
    "name": "Atomic Habits",
    "category": "Books",
    "brand": "James Clear",
    "price": 18,
    "color": "White",
    "pages": "320",
    "material": "Paperback",
    "rating": 4.8,
    "image": "📚"
  },
  {
    "id": 59,
    "name": "Sapiens: A Brief History of Humankind",
    "category": "Books",
    "brand": "Yuval Noah Harari",
    "price": 22,
    "color": "Beige",
    "pages": "464",
    "material": "Paperback",
    "rating": 4.7,
    "image": "📚"
  },
  {
    "id": 60,
    "name": "The Subtle Art of Not Giving a F*ck",
    "category": "Books",
    "brand": "Mark Manson",
    "price": 16,
    "color": "Orange",
    "pages": "224",
    "material": "Paperback",
    "rating": 4.5,
    "image": "📚"
  },
  {
    "id": 61,
    "name": "Hamilton Beach Toaster",
    "category": "Home & Kitchen",
    "brand": "Hamilton Beach",
    "price": 29,
    "color": "Silver",
    "capacity": "2 Slice",
    "material": "Metal",
    "rating": 4.3,
    "image": "🍞"
  },
  {
    "id": 62,
    "name": "Philips Air Fryer",
    "category": "Home & Kitchen",
    "brand": "Philips",
    "price": 129,
    "color": "Black",
    "capacity": "4.1L",
    "material": "Plastic",
    "rating": 4.6,
    "image": "🍟"
  },
  {
    "id": 63,
    "name": "Brita Water Pitcher",
    "category": "Home & Kitchen",
    "brand": "Brita",
    "price": 35,
    "color": "White",
    "capacity": "10 Cup",
    "material": "Plastic",
    "rating": 4.5,
    "image": "💧"
  },
  {
    "id": 64,
    "name": "Rubbermaid Food Storage Set",
    "category": "Home & Kitchen",
    "brand": "Rubbermaid",
    "price": 25,
    "color": "Clear",
    "capacity": "24 Piece",
    "material": "Plastic",
    "rating": 4.7,
    "image": "🧊"
  },
  {
    "id": 65,
    "name": "Cuisinart Chef's Knife",
    "category": "Home & Kitchen",
    "brand": "Cuisinart",
    "price": 18,
    "color": "Black",
    "capacity": "8 Inch",
    "material": "Stainless Steel",
    "rating": 4.6,
    "image": "🔪"
  },
  {
    "id": 66,
    "name": "Contigo Travel Mug",
    "category": "Home & Kitchen",
    "brand": "Contigo",
    "price": 17,
    "color": "Monaco",
    "capacity": "16oz",
    "material": "Stainless Steel",
    "rating": 4.7,
    "image": "☕"
  },
  {
    "id": 67,
    "name": "Logitech MX Master 4",
    "category": "Electronics",
    "brand": "Logitech",
    "price": 99,
    "color": "Graphite",
    "storage": "N/A",
    "material": "Plastic",
    "rating": 4.8,
    "image": "🖱️"
  },
  {
    "id": 68,
    "name": "Canon EOS Rebel T8i",
    "category": "Electronics",
    "brand": "Canon",
    "price": 899,
    "color": "Black",
    "storage": "32GB",
    "material": "Plastic",
    "rating": 4.7,
    "image": "📷"
  },
  {
    "id": 69,
    "name": "Kindle Paperwhite",
    "category": "Electronics",
    "brand": "Amazon",
    "price": 139,
    "color": "Black",
    "storage": "8GB",
    "material": "Plastic",
    "rating": 4.6,
    "image": "📖"
  },
  {
    "id": 70,
    "name": "GoPro HERO12",
    "category": "Electronics",
    "brand": "GoPro",
    "price": 399,
    "color": "Black",
    "storage": "64GB",
    "material": "Plastic",
    "rating": 4.7,
    "image": "📹"
  },
  {
    "id": 71,
    "name": "Reebok Classic Leather",
    "category": "Apparel",
    "brand": "Reebok",
    "price": 85,
    "color": "White",
    "size": "US 10",
    "material": "Leather",
    "rating": 4.4,
    "image": "👟"
  },
  {
    "id": 72,
    "name": "The North Face Backpack",
    "category": "Apparel",
    "brand": "The North Face",
    "price": 99,
    "color": "Black",
    "size": "30L",
    "material": "Nylon",
    "rating": 4.6,
    "image": "🎒"
  },
  {
    "id": 73,
    "name": "Gap Logo Hoodie",
    "category": "Apparel",
    "brand": "Gap",
    "price": 55,
    "color": "Navy",
    "size": "M",
    "material": "Cotton",
    "rating": 4.3,
    "image": "👕"
  },
  {
    "id": 74,
    "name": "Hanes Crew Socks 10-Pack",
    "category": "Apparel",
    "brand": "Hanes",
    "price": 18,
    "color": "White",
    "size": "L",
    "material": "Cotton Blend",
    "rating": 4.5,
    "image": "🧦"
  },
  {
    "id": 75,
    "name": "Uniqlo Ultra Light Down Jacket",
    "category": "Apparel",
    "brand": "Uniqlo",
    "price": 69,
    "color": "Black",
    "size": "M",
    "material": "Nylon",
    "rating": 4.6,
    "image": "🧥"
  },
  {
    "id": 76,
    "name": "Ray-Ban Wayfarer",
    "category": "Apparel",
    "brand": "Ray-Ban",
    "price": 149,
    "color": "Black",
    "size": "Standard",
    "material": "Plastic",
    "rating": 4.7,
    "image": "🕶️"
  },
  {
    "id": 77,
    "name": "Crocs Classic Clog",
    "category": "Apparel",
    "brand": "Crocs",
    "price": 45,
    "color": "Blue",
    "size": "US 9",
    "material": "Croslite",
    "rating": 4.4,
    "image": "🥿"
  },
  {
    "id": 78,
    "name": "Harry Potter and the Sorcerer's Stone",
    "category": "Books",
    "brand": "J.K. Rowling",
    "price": 10,
    "color": "Red",
    "pages": "320",
    "material": "Paperback",
    "rating": 4.9,
    "image": "📚"
  },
  {
    "id": 79,
    "name": "The Alchemist",
    "category": "Books",
    "brand": "Paulo Coelho",
    "price": 14,
    "color": "Yellow",
    "pages": "208",
    "material": "Paperback",
    "rating": 4.7,
    "image": "📚"
  },
  {
    "id": 80,
    "name": "Educated",
    "category": "Books",
    "brand": "Tara Westover",
    "price": 17,
    "color": "Blue",
    "pages": "352",
    "material": "Paperback",
    "rating": 4.8,
    "image": "📚"
  },
  {
    "id": 81,
    "name": "The Lean Startup",
    "category": "Books",
    "brand": "Eric Ries",
    "price": 20,
    "color": "White",
    "pages": "336",
    "material": "Paperback",
    "rating": 4.6,
    "image": "📚"
  },
  {
    "id": 82,
    "name": "Becoming",
    "category": "Books",
    "brand": "Michelle Obama",
    "price": 19,
    "color": "Black",
    "pages": "448",
    "material": "Hardcover",
    "rating": 4.8,
    "image": "📚"
  },
  {
    "id": 83,
    "name": "The Power of Habit",
    "category": "Books",
    "brand": "Charles Duhigg",
    "price": 16,
    "color": "Blue",
    "pages": "371",
    "material": "Paperback",
    "rating": 4.6,
    "image": "📚"
  },
  {
    "id": 84,
    "name": "Instant Vortex Air Fryer",
    "category": "Home & Kitchen",
    "brand": "Instant",
    "price": 99,
    "color": "Black",
    "capacity": "6 Quart",
    "material": "Plastic",
    "rating": 4.7,
    "image": "🍟"
  },
  {
    "id": 85,
    "name": "OXO Good Grips Salad Spinner",
    "category": "Home & Kitchen",
    "brand": "OXO",
    "price": 30,
    "color": "Green",
    "capacity": "6.22 Quart",
    "material": "Plastic",
    "rating": 4.8,
    "image": "🥗"
  },
  {
    "id": 86,
    "name": "Dyson Pure Cool Link",
    "category": "Home & Kitchen",
    "brand": "Dyson",
    "price": 399,
    "color": "White/Silver",
    "capacity": "N/A",
    "material": "Plastic",
    "rating": 4.6,
    "image": "🌀"
  },
  {
    "id": 87,
    "name": "Levoit Air Purifier",
    "category": "Home & Kitchen",
    "brand": "Levoit",
    "price": 89,
    "color": "White",
    "capacity": "N/A",
    "material": "Plastic",
    "rating": 4.7,
    "image": "🌬️"
  },
  {
    "id": 88,
    "name": "Simple Modern Water Bottle",
    "category": "Home & Kitchen",
    "brand": "Simple Modern",
    "price": 25,
    "color": "Midnight Black",
    "capacity": "32oz",
    "material": "Stainless Steel",
    "rating": 4.8,
    "image": "🥤"
  },
  {
    "id": 89,
    "name": "Anker PowerCore 20000",
    "category": "Electronics",
    "brand": "Anker",
    "price": 49,
    "color": "Black",
    "storage": "20000mAh",
    "material": "Plastic",
    "rating": 4.7,
    "image": "🔋"
  },
  {
    "id": 90,
    "name": "JBL Flip 6",
    "category": "Electronics",
    "brand": "JBL",
    "price": 129,
    "color": "Blue",
    "storage": "N/A",
    "material": "Plastic",
    "rating": 4.8,
    "image": "🔊"
  },
  {
    "id": 91,
    "name": "Samsung T7 Portable SSD",
    "category": "Electronics",
    "brand": "Samsung",
    "price": 119,
    "color": "Gray",
    "storage": "1TB",
    "material": "Aluminum",
    "rating": 4.9,
    "image": "💾"
  },
  {
    "id": 92,
    "name": "Sony Alpha a6400",
    "category": "Electronics",
    "brand": "Sony",
    "price": 998,
    "color": "Black",
    "storage": "64GB",
    "material": "Magnesium Alloy",
    "rating": 4.8,
    "image": "📷"
  },
  {
    "id": 93,
    "name": "Apple AirTag",
    "category": "Electronics",
    "brand": "Apple",
    "price": 29,
    "color": "White",
    "storage": "N/A",
    "material": "Plastic",
    "rating": 4.7,
    "image": "📍"
  },
  {
    "id": 94,
    "name": "Garmin Forerunner 255",
    "category": "Electronics",
    "brand": "Garmin",
    "price": 349,
    "color": "Slate Gray",
    "storage": "N/A",
    "material": "Plastic",
    "rating": 4.6,
    "image": "⌚"
  },
  {
    "id": 95,
    "name": "Patagonia Better Sweater",
    "category": "Apparel",
    "brand": "Patagonia",
    "price": 139,
    "color": "Gray",
    "size": "L",
    "material": "Fleece",
    "rating": 4.8,
    "image": "🧥"
  },
  {
    "id": 96,
    "name": "New Balance 574",
    "category": "Apparel",
    "brand": "New Balance",
    "price": 80,
    "color": "Gray",
    "size": "US 10",
    "material": "Suede",
    "rating": 4.7,
    "image": "👟"
  },
  {
    "id": 97,
    "name": "Timberland 6-Inch Boot",
    "category": "Apparel",
    "brand": "Timberland",
    "price": 198,
    "color": "Wheat",
    "size": "US 11",
    "material": "Leather",
    "rating": 4.8,
    "image": "🥾"
  },
  {
    "id": 98,
    "name": "Columbia Silver Ridge Pants",
    "category": "Apparel",
    "brand": "Columbia",
    "price": 60,
    "color": "Khaki",
    "size": "34W x 32L",
    "material": "Nylon",
    "rating": 4.6,
    "image": "👖"
  },
  {
    "id": 99,
    "name": "Calvin Klein Boxer Briefs 5-Pack",
    "category": "Apparel",
    "brand": "Calvin Klein",
    "price": 45,
    "color": "Black",
    "size": "M",
    "material": "Cotton",
    "rating": 4.7,
    "image": "🩲"
  },
  {
    "id": 100,
    "name": "Lululemon ABC Jogger",
    "category": "Apparel",
    "brand": "Lululemon",
    "price": 128,
    "color": "Black",
    "size": "L",
    "material": "Warpstreme",
    "rating": 4.8,
    "image": "👖"
  }
];

module.exports = products;
